import re
import os
import google.generativeai as genai

# Configure Gemini API key from environment variable
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# ----------------------------------------
# 🧠 Resume Improvement Suggestions
# ----------------------------------------
def get_improvement_suggestions(resume_text):
    """Analyzes the resume text and returns suggestions."""
    
    suggestions = []
    text_lower = resume_text.lower()
    
    # 1. Check for measurable achievements
    has_numbers = bool(re.search(r'\d+', resume_text))
    has_percentage = bool(re.search(r'%|percent', text_lower))
    has_currency = bool(re.search(r'\$|usd', text_lower))
    
    if not (has_numbers or has_percentage or has_currency):
        suggestions.append({
            "type": "Measurable Achievements",
            "message": "Add numbers or metrics (e.g., 'Improved performance by 30%').",
            "impact": "High"
        })
        
    # 2. Check for action verbs
    action_verbs = [
        "led", "managed", "developed", "created",
        "designed", "optimized", "implemented", "built"
    ]
    
    found_verbs = [verb for verb in action_verbs if verb in text_lower]
    
    if len(found_verbs) < 3:
        suggestions.append({
            "type": "Action Verbs",
            "message": "Use strong action verbs like Developed, Built, Implemented.",
            "impact": "Medium"
        })
        
    # 3. Check resume length
    word_count = len(resume_text.split())
    
    if word_count < 200:
        suggestions.append({
            "type": "Length",
            "message": "Your resume is too short. Add more details about projects and experience.",
            "impact": "Medium"
        })
        
    elif word_count > 1000:
        suggestions.append({
            "type": "Length",
            "message": "Your resume is too long. Keep it concise and relevant.",
            "impact": "Low"
        })
        
    # Default fallback
    if not suggestions:
        suggestions.append({
            "type": "General",
            "message": "Your resume looks good. Tailor it specifically to the job description.",
            "impact": "Good"
        })
        
    return suggestions


# ----------------------------------------
# 📊 Resume Strength Calculation
# ----------------------------------------
def calculate_resume_strength(ats_score, suggestions):
    """Calculates overall resume strength score + label + color."""
    
    strength_score = float(ats_score)
    penalty = 0
    
    for suggestion in suggestions:
        if suggestion["impact"] == "High":
            penalty += 10
        elif suggestion["impact"] == "Medium":
            penalty += 5
            
    final_score = max(0, min(100, strength_score - penalty + 20))
    
    # Label + Color
    if final_score >= 80:
        label = "Excellent 🌟"
        color = "green"
    elif final_score >= 60:
        label = "Good 👍"
        color = "orange"
    else:
        label = "Needs Work ⚠️"
        color = "red"
        
    return final_score, label, color


# ----------------------------------------
# 🤖 AI Chatbot (Gemini)
# ----------------------------------------
def generate_chatbot_response(user_input, ats_score, missing_skills, suggestions, resume_text, job_description):
    """Generates AI response using Gemini API."""
    
    try:
        # ✅ Use stable working model
        model = genai.GenerativeModel("gemini-pro")
        
        missing_skills_str = ", ".join(missing_skills) if missing_skills else "None"
        suggestions_str = "\n".join([f"- {s['message']}" for s in suggestions])
        
        # Limit text size
        resume_snippet = resume_text[:1500]
        jd_snippet = job_description[:1500]
        
        prompt = f"""
You are a professional resume coach and recruiter.

Analyze the resume and job description and answer the user's question.

Be:
- Clear
- Practical
- Beginner-friendly
- Actionable

--- CONTEXT ---
ATS Score: {ats_score}%
Missing Skills: {missing_skills_str}

Suggestions:
{suggestions_str}

--- RESUME ---
{resume_snippet}

--- JOB DESCRIPTION ---
{jd_snippet}

--- USER QUESTION ---
{user_input}

Provide helpful advice.
"""
        
        response = model.generate_content(prompt)
        
        # Safe response handling
        if hasattr(response, "text"):
            return response.text
        else:
            return "⚠️ No response generated by AI."
            
    except Exception as e:
        return """⚠️ AI feature is currently unavailable.

But here are quick suggestions based on your resume:

- Add missing skills from job description
- Improve ATS keywords
- Use strong action verbs (Developed, Built, Optimized)
- Add measurable achievements (numbers, %)

Tip: Try aligning your resume more closely with the job description."""